- name: Playbook for installing packages
  hosts: frontend
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{ item }}"
     state: installed
    loop:
    - nginx
    - mysql
    - zip  
     
